export var NAME_LIST = [
    {id:519,name:"Panchu Manandhar",amount:0},
    {id:47,name:"Sanu Manandhar",amount:0},
    {id:141,name:"Sangita Manandhar(S)",amount:0},
    {id:55,name:"Sangita Manandhar",amount:0},
    {id:441,name:"Rabina Manandhar",amount:0},
    {id:54,name:"Asta Manandhar",amount:0},
    {id:43,name:"Laxmi Maharjan",amount:0},
    {id:209,name:"Gyanlal Maharjan",amount:0},
    {id:213,name:"Tulsi Narayan Mdhr",amount:0},
    {id:540,name:"Shanti Gopali",amount:0},
    {id:28,name:"Gyan Maya Manandhar",amount:0},
    {id:29,name:"Arjun Manandhar",amount:0},
    {id:126,name:"Anup Manandhar",amount:0},
    {id:515,name:"Kamala Manandhar",amount:0},
    {id:7,name:"Balkumari Manandhar",amount:0},
    {id:44,name:"Nani Manandhar",amount:0},
    {id:503,name:"Jagatlal Manandhar",amount:0},
    {id:94,name:"Balkrishna Manandhar",amount:0},
    {id:45,name:"Sukraraj Manandhar",amount:0},
    {id:409,name:"Sahanshila Shrestha",amount:0},

    {id:536,name:"Dipak Khadgi",amount:0},
    {id:537,name:"Yogesh Khadgi",amount:0},
    {id:111,name:"Triratna Manandhar",amount:0},
    {id:526,name:"Dineshor Maharjan",amount:0},
    {id:161,name:"Dineshor Maharjan(S)",amount:0},
    {id:521,name:"Ishwari Khadgi",amount:0},
    
    
    {id:500,name:"Bimala Shrestha",amount:0},
    {id:221,name:"Shree Ram Mhr",amount:0},
    {id:241,name:"Rabi Shahi",amount:0},
    {id:263,name:"Sanuvai Maharjan",amount:0},
    {id:130,name:"Maya Lama",amount:0},
    {id:205,name:"Kabiraj Maharjan",amount:0},
    {id:59,name:"Surendra Manandhar",amount:0},
    {id:154,name:"Surendra Manandhar(S)",amount:0},
    {id:462,name:"Sudip Shrestha",amount:0},
    {id:371,name:"Laxman Acharya",amount:0},
    {id:147,name:"Kishor Bhandari",amount:0},
    {id:235,name:"Sita Khatri",amount:0},
    {id:433,name:"Rukmani Maharjan",amount:0},
    {id:236,name:"Birmaya Maharjan",amount:0},
    {id:449,name:"Ramesh Kumar Sth",amount:0},
    {id:350,name:"Rajesh Bdr Basnet",amount:0},
    {id:57,name:"Laxmi Narayan Mdhr",amount:0},
    
    {id:293,name:"Rajendra Gopali",amount:0},
    {id:49,name:"Kamala Mdhr (Nagau)",amount:0},
    {id:506,name:"Debit Deula",amount:0},
    {id:507,name:"Aiman Lama",amount:0},
    
    {id:510,name:"Lav Kumar Sth",amount:0},
    {id:508,name:"Manoj Singh",amount:0},
    {id:547,name:"Chandra Maya Thakuri",amount:0},
    
    {id:514,name:"Binod Shrestha",amount:0},
    {id:259,name:"Hari Saran Mhr",amount:0},
    {id:26,name:"Manikram Manandhar",amount:0},
    {id:212,name:"Bhim Bahadur Sth",amount:0},
    {id:525,name:"Ratna Dhwaj Mhr",amount:0},
    {id:512,name:"Kamala Maharjan",amount:0},
    {id:237,name:"Kamala Shrestha",amount:0},
    {id:416,name:"Grishma Shrestha",amount:0},
    
    
    {id:366,name:"Ajita Acharya",amount:0},
    {id:30,name:"Ratnakaji Manandhar",amount:0},
    {id:283,name:"Rani Chaudhary",amount:0},
    {id:491,name:"Rajendra Psd Kafle",amount:0},
    
    {id:234,name:"Nabina Pradhan",amount:0},
    {id:289,name:"Pabi Thapa",amount:0},
    {id:264,name:"Babin Pradhan",amount:0},
    {id:461,name:"Susma Kuwar",amount:0},
    
    
    {id:178,name:"Rabindra Shrestha",amount:0},
    
    {id:558,name:"Sita Devi Tamang",amount:0},
    {id:469,name:"Aryan Gole",amount:0},
    {id:555,name:"Pramod Karki",amount:0},
    {id:999,name:"Sunil Pradhan",amount:0},
    {id:888,name:"Sabina Maharjan",amount:0},
    {id:543,name:"Sanil Subodh",amount:0},
];